# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kristoff's IT Study
brief-intro: Let's Study every day!!!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kristoffDH.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_username:  kristoffDH
email: dhkristoff@gmail.com

description_footer: 

# comments
disqus_shortname: disqus_i5e1h9rb93

google_analytics_id: 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins:
  - jekyll-paginate
paginate: 6
